-- Internship & Placement Lifecycle Management — schema (Oracle 12c+)
-- Run as schema owner (e.g. IPMS_USER).

-- Clean reinstall (optional): uncomment if objects already exist
/*
BEGIN
  FOR r IN (SELECT t.table_name FROM user_tables t) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
*/

CREATE TABLE company (
  company_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(150) NOT NULL,
  sector       VARCHAR2(80),
  hq_city      VARCHAR2(80),
  CONSTRAINT uq_company_name UNIQUE (name)
);

CREATE TABLE student (
  student_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reg_no       VARCHAR2(20) NOT NULL,
  full_name    VARCHAR2(120) NOT NULL,
  branch       VARCHAR2(10)  NOT NULL,
  section      CHAR(1)       NOT NULL,
  cgpa         NUMBER(4,2)   NOT NULL,
  email        VARCHAR2(120),
  phone        VARCHAR2(20),
  CONSTRAINT uq_student_reg UNIQUE (reg_no),
  CONSTRAINT ck_student_cgpa CHECK (cgpa >= 0 AND cgpa <= 10)
);

CREATE TABLE opening (
  opening_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id    NUMBER NOT NULL,
  title         VARCHAR2(150) NOT NULL,
  opp_type      VARCHAR2(20)  NOT NULL,
  min_cgpa      NUMBER(4,2)   NOT NULL,
  package_lpa   NUMBER(10,2),
  stipend_kpm   NUMBER(10,2),
  deadline      DATE,
  status        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  CONSTRAINT fk_opening_company FOREIGN KEY (company_id) REFERENCES company (company_id),
  CONSTRAINT ck_opening_type CHECK (opp_type IN ('INTERNSHIP', 'PLACEMENT')),
  CONSTRAINT ck_opening_status CHECK (status IN ('OPEN', 'CLOSED')),
  CONSTRAINT ck_opening_min_cgpa CHECK (min_cgpa >= 0 AND min_cgpa <= 10),
  CONSTRAINT ck_opening_pkg CHECK (
    (opp_type = 'PLACEMENT' AND package_lpa IS NOT NULL AND package_lpa > 0)
    OR (opp_type = 'INTERNSHIP')
  )
);

CREATE TABLE application (
  application_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id       NUMBER NOT NULL,
  opening_id       NUMBER NOT NULL,
  status           VARCHAR2(30) DEFAULT 'APPLIED' NOT NULL,
  applied_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  offer_ctc_lpa    NUMBER(10,2),
  CONSTRAINT fk_app_student FOREIGN KEY (student_id) REFERENCES student (student_id),
  CONSTRAINT fk_app_opening FOREIGN KEY (opening_id) REFERENCES opening (opening_id),
  CONSTRAINT uq_app_once UNIQUE (student_id, opening_id),
  CONSTRAINT ck_app_status CHECK (
    status IN ('APPLIED','SHORTLISTED','INTERVIEW','OFFERED','REJECTED','ACCEPTED','WITHDRAWN')
  ),
  CONSTRAINT ck_offer_ctc CHECK (offer_ctc_lpa IS NULL OR offer_ctc_lpa > 0)
);

CREATE INDEX idx_app_student ON application (student_id);
CREATE INDEX idx_app_opening ON application (opening_id);
CREATE INDEX idx_app_status ON application (status);

COMMENT ON TABLE company IS 'Recruiting organizations';
COMMENT ON TABLE student IS 'Students eligible for drives';
COMMENT ON TABLE opening IS 'Internship or placement roles';
COMMENT ON TABLE application IS 'Student applications and pipeline status';
