-- Triggers: audit trail + business defaults (Lab 12)

CREATE TABLE application_audit (
  audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id  NUMBER NOT NULL,
  old_status      VARCHAR2(30),
  new_status      VARCHAR2(30),
  changed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  change_type     VARCHAR2(20) NOT NULL
);

CREATE OR REPLACE TRIGGER trg_app_status_audit
  AFTER INSERT OR UPDATE OF status ON application
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO application_audit (application_id, old_status, new_status, change_type)
    VALUES (:NEW.application_id, NULL, :NEW.status, 'INSERT');
  ELSIF UPDATING THEN
    IF NVL(:OLD.status, 'X') <> NVL(:NEW.status, 'X') THEN
      INSERT INTO application_audit (application_id, old_status, new_status, change_type)
      VALUES (:NEW.application_id, :OLD.status, :NEW.status, 'STATUS_CHANGE');
    END IF;
  END IF;
END;
/

-- When status becomes OFFERED or ACCEPTED for PLACEMENT, ensure offer_ctc_lpa is set from opening if missing
CREATE OR REPLACE TRIGGER trg_app_fill_offer_ctc
  BEFORE INSERT OR UPDATE OF status ON application
  FOR EACH ROW
DECLARE
  v_pkg NUMBER;
  v_ot  VARCHAR2(20);
BEGIN
  IF :NEW.status IN ('OFFERED', 'ACCEPTED') THEN
    SELECT o.opp_type, o.package_lpa
    INTO v_ot, v_pkg
    FROM opening o
    WHERE o.opening_id = :NEW.opening_id;

    IF v_ot = 'PLACEMENT' AND :NEW.offer_ctc_lpa IS NULL AND v_pkg IS NOT NULL THEN
      :NEW.offer_ctc_lpa := v_pkg;
    END IF;
  END IF;
END;
/

-- Prevent application if CGPA < minimum
CREATE OR REPLACE TRIGGER trg_check_cgpa_eligibility
  BEFORE INSERT ON application
  FOR EACH ROW
DECLARE
  v_cgpa NUMBER;
  v_min  NUMBER;
BEGIN
  SELECT cgpa INTO v_cgpa FROM student WHERE student_id = :NEW.student_id;
  SELECT min_cgpa INTO v_min FROM opening WHERE opening_id = :NEW.opening_id;
  
  IF v_cgpa < v_min THEN
    RAISE_APPLICATION_ERROR(-20001, 'Student CGPA ' || v_cgpa || ' is below the minimum ' || v_min || ' required for this opening.');
  END IF;
END;
/

-- Removed trg_prevent_multiple_accept due to ORA-04091 mutating table.
-- Logic is handled in pgk_placement and web backend.
